### ISSUE TITLE
Please use a "better" font

### ISSUE THREAD

**Issue by Felitendo** [KieranP/Github-Releases-Feed#1]
Hey there,
first off thank you for making this. It works pretty good for me.
My only issue with it is the font though. It's very thin and hard to read.
Therefore it would be great if you could change it to e.g. Arial or Calibri.

**Comment by KieranP** [comment]
@Felitendo Thank you for the feedback. I have pushed an update to change the font family to "Helvetica, Arial, sans-serif". I've also tweaked the styles of the release description contents to be more uniform.
